[package]
name = "learn_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }

sqlx = { version = "0.8", features = [ "runtime-tokio-rustls", "postgres"] }
chrono = "0.4.42"
